# Generated by Django 5.2.1 on 2025-05-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
