services:
  backend:
    build: .
    command: cd /Backend_API && python manage.py runserver 0.0.0.0:8000
    volumes:
       - ./Backend_API:/app/Backend_API
    ports:
      - "8000:8000"
    depends_on:
      - db    
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
 
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data: